# Generated by Django 4.2 on 2023-06-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Mісто')),
                ('gas_url', models.URLField(blank=True, verbose_name='природний газ')),
                ('gas_parser', models.CharField(choices=[('min', 'minfin'), ('oth', 'other')], default='min', max_length=3)),
                ('water_url', models.URLField(blank=True, verbose_name='водопостачання та водовідведення')),
                ('water_parser', models.CharField(choices=[('min', 'minfin'), ('oth', 'other')], default='min', max_length=3)),
                ('hotwater_url', models.URLField(blank=True, verbose_name='гаряча вода')),
                ('hotwater_parser', models.CharField(choices=[('min', 'minfin'), ('oth', 'other')], default='min', max_length=3)),
                ('electric_url', models.URLField(blank=True, verbose_name='електроенергія')),
                ('electric_parser', models.CharField(choices=[('min', 'minfin'), ('oth', 'other')], default='min', max_length=3)),
                ('heating_url', models.URLField(blank=True, verbose_name='опалення')),
                ('heating_parser', models.CharField(choices=[('min', 'minfin'), ('oth', 'other')], default='min', max_length=3)),
                ('date_check', models.DateTimeField(verbose_name='Дата последней проверки')),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва Постачальника')),
            ],
            options={
                'verbose_name': 'Постачальник',
                'verbose_name_plural': 'Постачальники',
            },
        ),
        migrations.CreateModel(
            name='UtilityTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_check', models.DateTimeField(verbose_name='Дата создания')),
                ('utility_type', models.CharField(choices=[('gasp', 'Поставка газу'), ('gasd', 'Доставка газу'), ('watr', 'Водопостачання та водовідведення'), ('hotw', 'Гаряча вода'), ('elec', 'Електроенергія'), ('heat', 'Опалення')], max_length=4, verbose_name='Тип послуги')),
                ('tariff_1', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Тариф 1')),
                ('description_tariff_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Опис тарифу 1')),
                ('tariff_2', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Тариф 2')),
                ('description_tariff_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Опис тарифу 2')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_rates.city')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility_rates.provider')),
            ],
            options={
                'verbose_name': 'Комунальний тариф',
                'verbose_name_plural': 'Комунальні тарифи',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='providers',
            field=models.ManyToManyField(blank=True, editable=False, related_name='groups', to='utility_rates.provider'),
        ),
    ]
