# Generated by Django 4.2 on 2023-06-19 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utility_rates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitytariff',
            name='date_check',
        ),
        migrations.AddField(
            model_name='utilitytariff',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='city',
            name='date_check',
            field=models.DateTimeField(verbose_name='Дата останньої перевірки'),
        ),
    ]
