# Generated by Django 4.2 on 2023-06-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility_rates', '0002_remove_utilitytariff_date_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='providers',
            field=models.ManyToManyField(blank=True, editable=False, related_name='groups', to='utility_rates.provider', verbose_name='Постачальник'),
        ),
    ]
